#URI: "https://username@bitbucket.org/posmachineteam/ezygentechnology-pos.git"
#destinationDirectoryPath: "C:\\SpeedUP\\SpeedUP\\customer"

URI: "C:\\SpeedUP\\SpeedUP\\customer"
destinationDirectoryPath: "C:\\SpeedUP\\SpeedUP\\Test"

